name: PEST Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
            path: ~/.composer/cache/files
            key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
            php-version: ${{ matrix.php }}
            tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-source --no-interaction --no-progress

      - name: Unit Tests
        run: composer test:unit
